### ISSUE TITLE
Question: Is the /var/lib/docker mount needed? 

### ISSUE THREAD

**Issue by Poeschl** [virtualzone/docker-container-stats#12]
Hi there, I'm trying to pack your project into an Home Assistant Addon to monitor the running containers on my smart home system. 

The given api to develop vor it only grants me access to the `docker.sock`socket and not the `/var/lib/docker` folder. Is your software also working without it and just not showing some stats? Or failing completely? 

FYI the addon is currently located here:https://github.com/Poeschl/Hassio-Addons/pull/139

**Comment by virtualzone** [comment]
Hi @Poeschl , mounting /var/lib/docker is actually not necessary. I've removed this from the readme. Thanks for your hint!

**Comment by Poeschl** [comment]
Thanks for the fast response.
