### ISSUE TITLE
Update docker schema format

### ISSUE THREAD

**Issue by D0tty** [virtualzone/docker-container-stats#4]
When I `docker pull docker pull weweave/docker-container-stats` I get this message:

```
Image docker.io/weweave/docker-container-stats:latest uses outdated schema1 manifest format. Please upgrade to a schema2 image for better future compatibility. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
```

**Comment by virtualzone** [comment]
@D0tty I've built new Docker images. Could you please check if these work?

Please note the new Docker repository: virtualzone/docker-container-stats
