### ISSUE TITLE
Mem usage stays 0

### ISSUE THREAD

**Issue by HansMolenveld** [virtualzone/docker-container-stats#5]
The mem usage stays zero. I am running the container on docker RPI. The reason why is that de unit are give by docker stats is KiB, MiB, GiB etc. This why the mem usage stil stays zero. See
![dockerstats](https://user-images.githubusercontent.com/35487936/80911031-f4e94c00-8d33-11ea-851b-b717c3061728.PNG)
![stats_gui](https://user-images.githubusercontent.com/35487936/80911034-f61a7900-8d33-11ea-8b7a-a825cad366e4.PNG)
I have a temporaly fix so the mem usage is visible. If you can see on the gui of the stats.

**Comment by chdanielmueller** [comment]
@HansMolenveld What is your fix? I encounter the same issue

**Comment by HansMolenveld** [comment]
> @HansMolenveld What is your fix? I encounter the same issue

The memory is calculated in the file stats. The docker stats give KiB is stead off KB etc. What I did is to change the code:
On row 16 of the file is the following code:
    if (unit == 'KB') {
        return value*1024;
    } else if (unit == 'MB') {
        return value*1024*1024;
    } else if (unit == 'GB') {
        return value*1024*1024*1024;
    } else if (unit == 'TB') {
        return value*1024*1024*1024*1024;
    }
I changed it in:
    if (unit == 'KB' || unit == 'KIB') {
        return value*1024;
    } else if (unit == 'MB' || unit == 'MIB') {
        return value*1024*1024;
    } else if (unit == 'GB' || unit == 'GIB') {
        return value*1024*1024*1024;
    } else if (unit == 'TB' || unit == 'TIB') {
        return value*1024*1024*1024*1024;
    }
This can be done in the running docker. But when you do you will see no change you have to restart the container (do not update because the the change is not there anymore. What I did was the changed file save outside docker and when there is an update (and the problem is still there) copy it back (Be sure that other lines are still the same). I hope that the change will be made fast.
